# Generated by Django 4.2.7 on 2025-08-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_processor', '0002_add_ml_models_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
