name: CI
 
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python 
        uses: actions/setup-python@v5 
        with: 
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps (lint only) 
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit 
      - name: Run flake8 
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
      - name: Run bandit 
        run: bandit -r csv_analyzer csv_processor 
 
  tests: 
    runs-on: ubuntu-latest 
    needs: lint 
    steps: 
      - uses: actions/checkout@v4 
        with:
          fetch-depth: 0
      - name: Setup Python 
        uses: actions/setup-python@v5 
        with: 
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pytest-cov 
      - name: Django migrations
        run: python manage.py migrate --noinput
      - name: Run tests 
        run: pytest --cov 
 
  docker: 
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest 
    needs: tests 
    permissions:
      contents: read
      packages: write
    steps: 
      - uses: actions/checkout@v4 
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3 
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3 
      - name: Login to GHCR 
        uses: docker/login-action@v3 
        with: 
          registry: ghcr.io 
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Build and push 
        uses: docker/build-push-action@v5 
        with: 
          context: . 
          file: dockerfile.txt
          push: true 
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
